version: '3'
services:
  nodejs-express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
      MONGO_INITDB_DATABASE: test

volumes:
  mongodb_data:
    driver: local
